# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateStdDistancePointers <- function(types, considerNaNs) {
    .Call('_geosom_CreateStdDistancePointers', PACKAGE = 'geosom', types, considerNaNs)
}

CreateStdDistancePointer <- function(type, considerNaNs) {
    .Call('_geosom_CreateStdDistancePointer', PACKAGE = 'geosom', type, considerNaNs)
}

ObjectDistances <- function(data, numVars, numNAs, distanceFunctions, weights) {
    .Call('_geosom_ObjectDistances', PACKAGE = 'geosom', data, numVars, numNAs, distanceFunctions, weights)
}

LayerDistances <- function(data, codes, uclassif, numVars, numNAs, distanceFunctions, weights) {
    .Call('_geosom_LayerDistances', PACKAGE = 'geosom', data, codes, uclassif, numVars, numNAs, distanceFunctions, weights)
}

RcppSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs, geo_x, geo_y, geo_limit) {
    .Call('_geosom_RcppSupersom', PACKAGE = 'geosom', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs, geo_x, geo_y, geo_limit)
}

RcppBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs) {
    .Call('_geosom_RcppBatchSupersom', PACKAGE = 'geosom', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs)
}

RcppParallelBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores) {
    .Call('_geosom_RcppParallelBatchSupersom', PACKAGE = 'geosom', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores)
}

RcppMap <- function(data, numVars, numNAs, codes, weights, distanceFunctions) {
    .Call('_geosom_RcppMap', PACKAGE = 'geosom', data, numVars, numNAs, codes, weights, distanceFunctions)
}

